### ISSUE TITLE
-ZTI always downloads the esd instead of choosing the custom wim.

### ISSUE THREAD

**Issue by oingobo** [OSDeploy/OSD#154]
I'm attempting to use OSDCloudUSB to lay down offline VLSC media, zero touch.  The .Wim is saved to the USB in E:\osdcloud\os\windows 23 H2\install.wim

I'm using the following command.  Edit-OSDCloudWinPE -StartOSDCloud "-OSName 'Windows 11 23H2 x64' -OSLanguage en-us -OSEdition Enterprise -OSActivation Volume -ZTI"

For some reason, the script wants to always pull an .ESD even though the Wim is located in the right spot and matches the global variables.

**Comment by AkosBakos** [comment]
Use this switch: -FindImageFile
https://www.osdcloud.com/archive/under-review/wim#findimagefile

**Comment by gwblok** [comment]
@oingobo, please respond if you still need assistance.  I typically start OSDCloud via a script instead of a single command line, which gives me a lot more power.

I have a sample of how I start OSDCloud:
https://github.com/gwblok/garytown/blob/master/Dev/CloudScripts/SettingOSDCloudVarsSample.ps1

I then use Edit-OSDCloudWinPE -startnet "https://win11.garytown.com"   which will trigger my scripts I keep on github.

**Comment by oingobo** [comment]
Thank you both for responding so quickly.

I needed to use volume media* (VLSC) and leverage -ZTI.  I ended up converting the install.wim from the VLSC the media to an ESD and renamed it the same as the windows 11 23h2 feature update esd.  This way your logic thinks the media on the USB drive is a cached copy.

The OSDCloudUSB process is now, boot from thumb and the next screen is Autopilot OOBE with the assigned username.

Thank you for all you do.

*Because we want to make WHFB enrollment optional in Entra ID only Windows 11 device.  This didn't come until April release.
