### ISSUE TITLE
OSDCloud 24.9.17.1 Invoke-Webrequest

### ISSUE THREAD

**Issue by MDMEverything** [OSDeploy/OSD#168]
**Describe the bug**
When booting to WinPE the script stops before it can get the webscript url, its the Invoke-Webrequest that fails.

![image](https://github.com/user-attachments/assets/db69c647-7d80-4fcb-a377-3ea09299d9d4) 
This is the error when actually booting into WinPE

**To Reproduce**
Add webscript and supply URL when creating the bootimage
Boot and the error should appear

**Desktop (please complete the following information):**
 - OSDCloud 24.9.17.1

**Additional context**
It looks like there is a problem when sending a system.byte[] to the parameter that expects system.string
![image](https://github.com/user-attachments/assets/c07c1884-66ed-4d9e-b892-cb7e943ac3f2)

**Comment by Baldderick** [comment]
Identical issue here this morning also.

**Comment by MDMEverything** [comment]
Looks like the error was introduced in this pull https://github.com/OSDeploy/OSD/pull/162

**Comment by joebartlett94** [comment]
Hi everyone,

This issue is caused when the 'Content-Type' header returned by the server hosting the PowerShell script is set to 'application/octet-stream'. This is the default MIME type used by Azure Blob Storage, which I'm guessing many of us are using to host these files.

You can fix the problem by going into the Azure portal, selecting the file, and changing the 'CONTENT-TYPE' property to 'text/plain'.

![OSDCloud Blob Content Type](https://github.com/user-attachments/assets/0dfaa5a0-d647-41a1-a198-d6b27604f44c)

I'd suggest it may also be worthwhile updating the Invoke-WebPSScript.ps1 code to look out for 'application/octet-stream' responses and decode them back to text if possible using:
`[System.Text.Encoding]::UTF8.GetString($WebPSCommand)`

**Comment by StevenVBeek** [comment]
@gwblok

**Comment by gwblok** [comment]
I don't do any hosting of my content in Azure, so I have not experienced this issue in any of my testing.

If someone who can replicate would like to create another pull request with the fix, I'd be happy to merge.

Or if people prefer, I can revert the merge and undo changes from PR 162

 @OSDeploy will have to pull the trigger on creating a new module once fixes are done on GitHub

**Comment by sultanberisa** [comment]
> I don't do any hosting of my content in Azure, so I have not experienced this issue in any of my testing.
> 
> If someone who can replicate would like to create another pull request with the fix, I'd be happy to merge.
> 
> Or if people prefer, I can revert the merge and undo changes from PR 162
> 
> @OSDeploy will have to pull the trigger on creating a new module once fixes are done on GitHub

Please revert the merge and undo the changes if possible - i've managed to make it "work" but it WILL not work completely as intended in the current state - the code runs in a "broken" state if you will, invoke-expression is meant to be used for commandlets and not scriptblocks, which are two different things, especially when the script is 1100+ lines. 😄

**Comment by gwblok** [comment]
pull 162 has been reverted.

As a work around, you can grab the 2 scripts on github and replace in your module until @OSDeploy updates the module again to release a new verison.

**Comment by sultanberisa** [comment]
I see - so it won't get updated in PSGallery until @OSDeploy updates the module, and we have to manually replace the scripts in the meanwhile? 

Is there any ETA for when the remediated version of the module would get pushed to PSGallery?

**Comment by jwinterberg** [comment]
Just getting around to read in here after vacation and I have to see this...

I thought providing the ContentType in the Invoke-WebRequest would make it that it this wouldn't happen,
but it turns out that the Content-Type header is only relevant for POST/PUT/PATCH and is ignored in a GET request
according to the HTTP standards.

The fix would probably just be to detect the output type and then do the [System.Text.Encoding]::UTF8.GetString() as @joebartlett94 suggested.

I'll take a second try at it at some point, with a lot more testing and without adding the extra functionality directly to be safe.
