### ISSUE TITLE
Failed to add package

### ISSUE THREAD

**Issue by smarbar** [OSDeploy/OSD#29]
When creating a new OSDCloud template with WinRE I am getting a lot of failed to add package errors with code 0x800f081e. This seems to mean that the package is not applicable to the image but when I try to boot from the USB image created from this template it doesn't launch into PowerShell and says PowerShell is not recognized (One of the errors is for PowerShell)

![IMG_0489](https://user-images.githubusercontent.com/30940685/172888295-73684909-dceb-4aa1-8f72-9f61a32e67e4.JPEG)

I have tried creating it with Windows 10 on a physical device as well as a VM but both have the same issue. 

If I create one without the WinRE switch, everything works as expected but would really like to get the WiFi working.

**Comment by OSDeploy** [comment]
This error happens when ADK doesn't match the WIM OS you are servicing.  So if you are using the Windows 11 ADK, your computer needs to be on Windows 11 to use WinRE.  If you are on Windows 10, you need the Windows 10 ADK installed to service your WinRE as that is Windows 10 based.  Error Code shows it is not applicable.

**Comment by smarbar** [comment]
thanks, installed the adk for Win 10 2004 and all works now

**Comment by cubicsolutionsde** [comment]
I have the same issue, but i have my running OS Version and the ADK Version matching.
Windows 11 23H2 (22631.3007) with the ADK 10.1.25398.1

When I create a new OSDCloud Template without the WinRE Option the script runs through without any errors
