### ISSUE TITLE
Add support for local ESD files

### ISSUE THREAD

**Issue by Dirk-Manderin** [OSDeploy/OSD#85]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
The ability for OSD to recognize Windows ESD image files stored on the USB or ISO by their extension, and not just files with the WIM extension.

**Describe alternatives you've considered**
It is possible to rename the ESD file extension to WIM, but it would be cleaner if it was just recognized automatically.

**Additional context**

**Comment by gwblok** [comment]
I like this idea.  I'll have to think for awhile how to do this.  It gets complicated since the we use MS Catalog .esd files, which could already be sync'd to your drive.  So basically, I'd have to look for esd files that don't match anything in the current catalog, and make those available for you to use.

Are you hoping that they would show up in the drop down list in Start-OSDCloudGUI, or that you'd you set a variable with the ESD name, and then call Start-OSDCloud ?

**Comment by gwblok** [comment]
In Progress.  My Testing has worked well.
ESD Files must be in the OSDCloud\OS folder on the USB Drive for the process to find them.

Hopefully this enhancement will be in the next Module Release.

**Comment by gwblok** [comment]
This has been added to Module 24.1.3.1
Please test and reopen if you have issues
