### ISSUE TITLE
Cannot install 'Windows 10 21H2 de-de Volume'

### ISSUE THREAD

**Issue by AkosBakos** [OSDeploy/OSD#94]
Cannot install this release:
![1](https://github.com/OSDeploy/OSD/assets/44706641/1d7c7865-cbbb-42d9-9144-26d154c4fb92)

Even in the https://github.com/OSDeploy/OSD/blob/master/Catalogs/CloudOperatingSystems.json file is here:
![2](https://github.com/OSDeploy/OSD/assets/44706641/df35c83e-e4d6-49f6-b9fa-d30cc1dbdf70)

Get-OSDCloudOperatingSystems result is empty:
![3](https://github.com/OSDeploy/OSD/assets/44706641/2df7d031-3ad9-48b4-8de2-9f183261d0fb)

**Comment by gwblok** [comment]
When I made the changes last week, anything older than Win10 22H2 was not available.
I've since (Today) modified it to incorporate the old ESDs from the previous method, plus the new ESDs from the new method.  
This was a request because some still wanted to deploy Win10 21H2

The next time the Module is updated, older versions of 10 will be available.

**Comment by gwblok** [comment]
This should be resolved now.  Please reopen if it is not.

**Comment by HWZAdministrator** [comment]
I've tested now and can verify it works: Windows 10 21H2 de-DE

**Comment by AkosBakos** [comment]
I've tested now and can verify it works: Windows 10 21H2 de-DE
