### ISSUE TITLE
Shutdown after First Boot / before OOBE starts

### ISSUE THREAD

**Issue by NorbertBauer** [OSDeploy/OSD#96]
May I have not found the option, but it would be great to have the possibility to prepare Devices and shutdown after first boot. So it would be easier to have devices preinstalled and only the Autopilot will need to run, after Windows and drivers are already finished and the device is shipped to the enduser in a similar state, as it would be from factory.

I am not sure, if the process works by using the audit mode for the installation of drivers and the last command is "sysprep /oobe". But if so, then it would be great to have the option to add the "shutdown" parameter to the sysprep command, instead of the default "reboot" parameter.

**Comment by gwblok** [comment]
So basically you're asking, after everything is complete, and it's sitting at the OOBE screen, that it would just shutdown?

**Comment by NorbertBauer** [comment]
Yes. After that, it will be sent to User and he should finish the one.

**Comment by Abe-Telo** [comment]
So trying to understand your request, So instead i will give you all the answers i know. 
If your using Autounattend.xml then you can add a command to run scripts. Since you mentioned that you want autopiloted to run on next boot, i assume you do not want the behavior of shutdown. In that case you can try adding a package in OSDCloud/Automate/Provisioning/ File ending name .ppkg.  I use a script to connect to wifi, I believe it runs together with drivers if i am mistaken, then it runs on first boot. so somthing like "shutdown -s -t 120 "  could do the trick for you

if you don't know how to create a  .ppkg, let me know and i will lookit up on how i did it.

**Comment by gwblok** [comment]
I've built and tested this functionality in "test", and it's working well.
Basically, you set a variable, and it will shutdown the device at the end of SetupComplete stage.

ShutdownSetupComplete = [bool]$true

You can look at this sample script on how to preset OSDCloud Variables and trigger OSDCloud
https://github.com/gwblok/garytown/blob/master/Dev/CloudScripts/SettingOSDCloudVarsSample.ps1

This update should be in the next release of OSDCloud Module

**Comment by gwblok** [comment]
This is now included in Module 24.1.3.1
Set the variable before you start OSDCloud, and it will shutdown at the end of Setup Complete, so when you turn it on, it starts right at the OOBE screen for "is this the right country or region?"

ShutdownSetupComplete = [bool]$true 

See previous comment for examples to use.
